dataset:
  yaml_path: "data/raw/fire_smoke_yolo/data.yaml"

model:
  base_model: "yolo11n.pt"

training:
  epochs: 30
  image_size: 640
  batch_size: 4
  workers: 2
  device: "auto"
  project: "outputs/ultralytics_runs/fire_smoke"
  run_name: "fire_smoke_yolo_finetune"
  patience: 5

output:
  model_dir: "models/fire_smoke"
  best_model_name: "best_fire_smoke.pt"
  last_model_name: "last_fire_smoke.pt"
